name: Security scanning
on:
  workflow_call:
    # This example has flow2 define its inputs,
    # which is better for matrix strategies.
    # If you prefer to have flow1 define outputs, check the docs for an example.
    # inputs:  
    #   version:
    #     type: string
    #     required: true

jobs: 
  antivirus: 
    runs-on: ubuntu-latest
    name: Antivirus
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Git AV Scan
      uses: djdefi/gitavscan@main
      with:
        full: '--full'

  # sonarqube:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       # Disabling shallow clones is recommended for improving the relevancy of reporting
  #       fetch-depth: 0
  #   - name: SonarQube Scan
  #     uses: SonarSource/sonarqube-scan-action@5 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
  #     env:
  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}


  lint: 
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: first-step
        run : | 
          echo "all normal"
  saas: 
    runs-on: ubuntu-latest
    name: SAAS
    steps:
      - name: first-step
        run : | 
          echo "all normal"

  dast: 
    runs-on: ubuntu-latest
    name: DAST
    steps:
      - name: first-step
        run : | 
          echo "all normal"
  yast: 
    runs-on: ubuntu-latest
    name: YAST
    steps:
      - name: first-step
        run : | 
          echo "all normal"