name: Test
on:
  workflow_call:
    inputs:  
      version:
        type: string
        required: true

env:
  LABEL_TEST: test-passed

jobs: 
  unit: 
    name: Unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: | 
          echo "simple run test"

  smoke: 
    name: Smoke-test 
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: | 
          echo "simple run test"
  
  fazz:
    name: Fazzing 
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: | 
          echo "simple run test"

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: | 
          echo "simple run test"

  regress:
    name: Regress
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: | 
          echo "simple run test"

  change-label:
    needs: [regress, integration, fazz, smoke, unit]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Find associated PR
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            // Ищем PR для текущей ветки
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            });
            return prs[0]?.number || 0;
  
      - name: Add test-passed label
        if: steps.find-pr.outputs.result != 0
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: ${{ steps.find-pr.outputs.result }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['test-passed']
            });
            console.log('Added test-passed label to PR #${{ steps.find-pr.outputs.result }}');
  
      - name: Skip label (no PR found)
        if: steps.find-pr.outputs.result == 0
        run: echo "No open PR found for this branch, skipping label"
            
